services:
    kanbano:
        build:
            context: .
            dockerfile: ./Dockerfile
            cache_from:
                - node:24-alpine
                - caddy:2-alpine
        container_name: kanbano
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.kanbano.rule=Host(`kanbano.fr`)"
            - "traefik.http.routers.kanbano.entrypoints=websecure"
            - "traefik.http.routers.kanbano.tls=true"
            - "traefik.http.routers.kanbano.tls.certresolver=letsencrypt"
            - "traefik.http.routers.kanbano-http.rule=Host(`kanbano.fr`)"
            - "traefik.http.routers.kanbano-http.entrypoints=web"
            - "traefik.http.routers.kanbano-http.middlewares=redirect-https"
            - "traefik.http.middlewares.redirect-https.redirectscheme.scheme=https"
            - "traefik.http.services.kanbano.loadbalancer.server.port=80"

        networks:
            - dokploy-network
        restart: always

networks:
    dokploy-network:
        external: true
